model_name: resnet20
private_task: cifar10
public_task: cifar100
num_clients: 100
global_round: 2000
sample_ratio: 1.0
partition: dirichlet
dir_alpha: 0.05
seed: 42
public_size: 10000
public_size_per_round: 1000
epochs: 5
batch_size: 100
lr: 0.1
kd_epochs: 5
kd_batch_size: 100
kd_lr: 0.1
num_parallels: 10
dataset_root_dir: /tmp/scarlet/dataset
dataset_split_dir: /tmp/scarlet/split
share_dir: /tmp/scarlet/share
state_dir: /tmp/scarlet/state
